minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.11'
  - eslint@10.9.0
  - vue-tsc@3.3.11
shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - undici-types@6.21.0
packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  vue-demi: true
