import { z } from 'zod'
import { defineSettingsDomain } from '../registry'

export const DiscordSettingsSchema = z.object({
	enabled: z.boolean().default(false),
	guildId: z.string().default(''),
	rolesAutoBestowEnabled: z.boolean().default(false),
	rolesAutoBestowRoles: z.string().default(''),
	moderationLogEnabled: z.boolean().default(false),
	moderationLogChannelId: z.string().default(''),
	eventJoinEnabled: z.boolean().default(false),
	eventJoinChannelId: z.string().default(''),
	eventLeaveEnabled: z.boolean().default(false),
	eventLeaveChannelId: z.string().default(''),
	alertFollowEnabled: z.boolean().default(false),
	alertFollowChannelId: z.string().default(''),
	alertSubEnabled: z.boolean().default(false),
	alertSubChannelId: z.string().default(''),
	alertGiftEnabled: z.boolean().default(false),
	alertGiftChannelId: z.string().default(''),
	alertCheerEnabled: z.boolean().default(false),
	alertCheerChannelId: z.string().default(''),
	alertRaidEnabled: z.boolean().default(false),
	alertRaidChannelId: z.string().default(''),
	alertLiveEnabled: z.boolean().default(false),
	alertLiveChannelId: z.string().default(''),
	alertLiveRemoveOffline: z.boolean().default(false),
	alertLiveLastMessageId: z.string().default(''),
	alertLiveLastChannelId: z.string().default(''),
	alertOfflineEnabled: z.boolean().default(false),
	alertOfflineChannelId: z.string().default(''),
	alertBanEnabled: z.boolean().default(false),
	alertBanChannelId: z.string().default(''),
	alertTimeoutEnabled: z.boolean().default(false),
	alertTimeoutChannelId: z.string().default(''),
	alertUnbanEnabled: z.boolean().default(false),
	alertUnbanChannelId: z.string().default(''),
	alertMessageDeleteEnabled: z.boolean().default(false),
	alertMessageDeleteChannelId: z.string().default(''),
})

export type DiscordSettings = z.infer<typeof DiscordSettingsSchema>

export const discordSettings = defineSettingsDomain({
	namespace: 'discord',
	schema: DiscordSettingsSchema,
	customKeys: {
		enabled: 'discord.enabled',
		guildId: 'discord.guild_id',
		rolesAutoBestowEnabled: 'discord.roles.auto_bestow_enabled',
		rolesAutoBestowRoles: 'discord.roles.auto_bestow_roles',
		moderationLogEnabled: 'discord.moderation.log.enabled',
		moderationLogChannelId: 'discord.moderation.log.channel_id',
		eventJoinEnabled: 'discord.events.join.enabled',
		eventJoinChannelId: 'discord.events.join.channel_id',
		eventLeaveEnabled: 'discord.events.leave.enabled',
		eventLeaveChannelId: 'discord.events.leave.channel_id',
		alertFollowEnabled: 'discord.alerts.follow.enabled',
		alertFollowChannelId: 'discord.alerts.follow.channel_id',
		alertSubEnabled: 'discord.alerts.sub.enabled',
		alertSubChannelId: 'discord.alerts.sub.channel_id',
		alertGiftEnabled: 'discord.alerts.gift.enabled',
		alertGiftChannelId: 'discord.alerts.gift.channel_id',
		alertCheerEnabled: 'discord.alerts.cheer.enabled',
		alertCheerChannelId: 'discord.alerts.cheer.channel_id',
		alertRaidEnabled: 'discord.alerts.raid.enabled',
		alertRaidChannelId: 'discord.alerts.raid.channel_id',
		alertLiveEnabled: 'discord.alerts.live.enabled',
		alertLiveChannelId: 'discord.alerts.live.channel_id',
		alertLiveRemoveOffline: 'discord.alerts.live.remove_offline',
		alertLiveLastMessageId: 'discord.alerts.live.last_message_id',
		alertLiveLastChannelId: 'discord.alerts.live.last_channel_id',
		alertOfflineEnabled: 'discord.alerts.offline.enabled',
		alertOfflineChannelId: 'discord.alerts.offline.channel_id',
		alertBanEnabled: 'discord.alerts.ban.enabled',
		alertBanChannelId: 'discord.alerts.ban.channel_id',
		alertTimeoutEnabled: 'discord.alerts.timeout.enabled',
		alertTimeoutChannelId: 'discord.alerts.timeout.channel_id',
		alertUnbanEnabled: 'discord.alerts.unban.enabled',
		alertUnbanChannelId: 'discord.alerts.unban.channel_id',
		alertMessageDeleteEnabled: 'discord.alerts.message_delete.enabled',
		alertMessageDeleteChannelId: 'discord.alerts.message_delete.channel_id',
	},
})
