import { z } from 'zod'
import { defineSettingsDomain } from '../registry'

export const DiscordSettingsSchema = z.object({
	enabled: z.boolean().default(false),
	guildId: z.string().default(''),
	rolesAutoBestowEnabled: z.boolean().default(false),
	rolesAutoBestowRoles: z.string().default(''),
	moderationLogEnabled: z.boolean().default(false),
	moderationLogChannelId: z.string().default(''),
	eventJoinEnabled: z.boolean().default(false),
	eventJoinChannelId: z.string().default(''),
	eventJoinTemplate: z.string().default('Welcome to {server}, {user}!'),
	eventLeaveEnabled: z.boolean().default(false),
	eventLeaveChannelId: z.string().default(''),
	eventLeaveTemplate: z.string().default('{username} has left the server.'),
	alertFollowEnabled: z.boolean().default(false),
	alertFollowChannelId: z.string().default(''),
	alertFollowTemplate: z.string().default('Thank you for the follow, $(sender)!'),
	alertSubEnabled: z.boolean().default(false),
	alertSubChannelId: z.string().default(''),
	alertSubTemplate: z.string().default('Thank you for subscribing, $(sender)! Welcome to the club!'),
	alertGiftEnabled: z.boolean().default(false),
	alertGiftChannelId: z.string().default(''),
	alertGiftTemplate: z.string().default('Thank you @$(sender) for gifting $(giftCount) sub(s) to the community!'),
	alertCheerEnabled: z.boolean().default(false),
	alertCheerChannelId: z.string().default(''),
	alertCheerTemplate: z.string().default('Thank you @$(sender) for cheering $(bitsCount) bits! $(cheerMessage)'),
	alertRaidEnabled: z.boolean().default(false),
	alertRaidChannelId: z.string().default(''),
	alertRaidTemplate: z.string().default('$(sender) is raiding us with $(raidSize) viewers!'),
	alertLiveEnabled: z.boolean().default(false),
	alertLiveChannelId: z.string().default(''),
	alertLiveTemplate: z.string().default('@everyone $(sender) is now live on Twitch!'),
	alertLiveRemoveOffline: z.boolean().default(false),
	alertLiveLastMessageId: z.string().default(''),
	alertLiveLastChannelId: z.string().default(''),
	alertOfflineEnabled: z.boolean().default(false),
	alertOfflineChannelId: z.string().default(''),
	alertOfflineTemplate: z.string().default('The stream has ended. Thanks for watching!'),
	alertBanEnabled: z.boolean().default(false),
	alertBanChannelId: z.string().default(''),
	alertBanTemplate: z.string().default('$(sender) has been banned from the channel.'),
	alertTimeoutEnabled: z.boolean().default(false),
	alertTimeoutChannelId: z.string().default(''),
	alertTimeoutTemplate: z.string().default('$(sender) has been timed out for $(duration) seconds.'),
	alertUnbanEnabled: z.boolean().default(false),
	alertUnbanChannelId: z.string().default(''),
	alertUnbanTemplate: z.string().default('$(sender) has been unbanned.'),
	alertMessageDeleteEnabled: z.boolean().default(false),
	alertMessageDeleteChannelId: z.string().default(''),
	alertMessageDeleteTemplate: z.string().default('A message from $(sender) was deleted.'),
})

export type DiscordSettings = z.infer<typeof DiscordSettingsSchema>

export const discordSettings = defineSettingsDomain({
	namespace: 'discord',
	schema: DiscordSettingsSchema,
	customKeys: {
		enabled: 'discord.enabled',
		guildId: 'discord.guild_id',
		rolesAutoBestowEnabled: 'discord.roles.auto_bestow_enabled',
		rolesAutoBestowRoles: 'discord.roles.auto_bestow_roles',
		moderationLogEnabled: 'discord.moderation.log.enabled',
		moderationLogChannelId: 'discord.moderation.log.channel_id',
		eventJoinEnabled: 'discord.events.join.enabled',
		eventJoinChannelId: 'discord.events.join.channel_id',
		eventJoinTemplate: 'discord.events.join.template',
		eventLeaveEnabled: 'discord.events.leave.enabled',
		eventLeaveChannelId: 'discord.events.leave.channel_id',
		eventLeaveTemplate: 'discord.events.leave.template',
		alertFollowEnabled: 'discord.alerts.follow.enabled',
		alertFollowChannelId: 'discord.alerts.follow.channel_id',
		alertFollowTemplate: 'discord.alerts.follow.template',
		alertSubEnabled: 'discord.alerts.sub.enabled',
		alertSubChannelId: 'discord.alerts.sub.channel_id',
		alertSubTemplate: 'discord.alerts.sub.template',
		alertGiftEnabled: 'discord.alerts.gift.enabled',
		alertGiftChannelId: 'discord.alerts.gift.channel_id',
		alertGiftTemplate: 'discord.alerts.gift.template',
		alertCheerEnabled: 'discord.alerts.cheer.enabled',
		alertCheerChannelId: 'discord.alerts.cheer.channel_id',
		alertCheerTemplate: 'discord.alerts.cheer.template',
		alertRaidEnabled: 'discord.alerts.raid.enabled',
		alertRaidChannelId: 'discord.alerts.raid.channel_id',
		alertRaidTemplate: 'discord.alerts.raid.template',
		alertLiveEnabled: 'discord.alerts.live.enabled',
		alertLiveChannelId: 'discord.alerts.live.channel_id',
		alertLiveTemplate: 'discord.alerts.live.template',
		alertLiveRemoveOffline: 'discord.alerts.live.remove_offline',
		alertLiveLastMessageId: 'discord.alerts.live.last_message_id',
		alertLiveLastChannelId: 'discord.alerts.live.last_channel_id',
		alertOfflineEnabled: 'discord.alerts.offline.enabled',
		alertOfflineChannelId: 'discord.alerts.offline.channel_id',
		alertOfflineTemplate: 'discord.alerts.offline.template',
		alertBanEnabled: 'discord.alerts.ban.enabled',
		alertBanChannelId: 'discord.alerts.ban.channel_id',
		alertBanTemplate: 'discord.alerts.ban.template',
		alertTimeoutEnabled: 'discord.alerts.timeout.enabled',
		alertTimeoutChannelId: 'discord.alerts.timeout.channel_id',
		alertTimeoutTemplate: 'discord.alerts.timeout.template',
		alertUnbanEnabled: 'discord.alerts.unban.enabled',
		alertUnbanChannelId: 'discord.alerts.unban.channel_id',
		alertUnbanTemplate: 'discord.alerts.unban.template',
		alertMessageDeleteEnabled: 'discord.alerts.message_delete.enabled',
		alertMessageDeleteChannelId: 'discord.alerts.message_delete.channel_id',
		alertMessageDeleteTemplate: 'discord.alerts.message_delete.template',
	},
})
